spring:
  application:
    name: client
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
    mcp:
      client:
        sse:
          connections:
            mcp-http-sse:
              url: http://localhost:8095
logging:
  level:
    org:
      springframework:
        ai: DEBUG

#  main:
#    banner-mode: off
#logging:
#  level:
#    root: off